db:
  name: pgdb01
  group: pgdb01
  instances: 1
  size: 8000Gi
  superUser:
    usernameKey: username
    passwordKey: password
    replicationUserKey: repuser
    replicationPassKey: reppass
    secretPath: gdex/pgdb01
  resource:
    limits:
      cpu: '16'
      memory: 128Gi
  
  backups:
    volumeSnapshot:
      enabled: true
      snapshotClassName: csi-rbdplugin-snapclass
    s3:
      enabled: false
