{{- if .Values.db.backups.s3.enabled }}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: boreas
spec:
  configuration:
    destinationPath: {{ .Values.db.backups.s3.destinationPath }}
    endpointURL: {{ .Values.db.backups.s3.endpointURL }}
    s3Credentials:
      accessKeyId:
        name: {{ .Values.db.backups.s3.secretName }}
        key: access_key
      secretAccessKey:
        name: {{ .Values.db.backups.s3.secretName }}
        key: secret_key
    wal:
      compression: bzip2
{{- end }}