apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Values.db.name }}-weekly-backup
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.db.name }}
spec:
  # Schedule: Roughly midnight local time 
  schedule: "0 5 * * *"
  
  backupOwnerReference: self
  
  cluster:
    name: {{ .Values.db.name }}
  
  target: primary
  method: barmanObjectStore
