apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: gdex-app-team
  namespace: rda
  labels:
    alertmanagerConfig: gdex
    namespace: rda
spec:
  route:
    receiver: gdex-app-team
    groupBy:
      - alertname
    groupWait: 10s
    groupInterval: 1m
    repeatInterval: 60m 
    matchers:
      - name: namespace
        value: rda
        matchType: "="
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            value: InfoInhibitor
            matchType: "="
      - receiver: "null"
        matchers:
          - name: deployment
            value: (riley|chiaweih|dattore)-.*
            matchType: "=~"

  receivers:
    - name: gdex-app-team
      emailConfigs:
        - to: 'zji@ucar.edu, rpconroy@ucar.edu'
          from: alertmanager@k8s.ucar.edu
          smarthost: vdir.ucar.edu:25  
    - name: "null"
