apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backup-s3-creds
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Values.db.backups.s3.secretPath }}
      property: access_key
    secretKey: access_key
  - remoteRef:
      key: {{ .Values.db.backups.s3.secretPath }}
      property: secret_key
    secretKey: secret_key
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: rda-ro
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ .Values.db.backups.s3.secretName }}
        
